import 'gamepad_service.dart';

/// Database of hardware-specific mappings for various controllers and modes.
/// Following the SDL2 gamecontrollerdb pattern.
const Map<String, Map<String, GameAction>> kControllerMappings = {
  // 8BitDo Micro - Switch mode (macOS IOKit)
  '8BitDo Micro': {
    'a.circle': GameAction.confirm,
    'b.circle': GameAction.back,
    'x.circle': GameAction.detail,
    'y.circle': GameAction.favorite,
    'l.joystick - yAxis': GameAction.verticalAxis,
    'l.joystick - xAxis': GameAction.horizontalAxis,
  },

  // 8BitDo Micro - D mode (Generic D-Input)
  '8BitDo Micro gamepad': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
  },

  // Xbox Controllers (Windows XInput / Generic Bluetooth)
  'Xbox': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'start': GameAction.start,
    'back': GameAction.select,
    'button_6': GameAction.select,
    'button_7': GameAction.start,
  },

  // Xbox One / Series X|S (reports as "Xbox One" or similar)
  'Xbox One': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'start': GameAction.start,
    'back': GameAction.select,
    'button_6': GameAction.select,
    'button_7': GameAction.start,
  },

  // Nintendo Switch Pro Controller - XInput / SDL named button variants
  'Nintendo Switch Pro Controller': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
    'button_8': GameAction.start,
    'button_9': GameAction.select,
  },

  // Joy-Con (L)
  'Joy-Con (L)': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'leftstick': GameAction.horizontalAxis,
    'button_minus': GameAction.select,
    'button_8': GameAction.select,
  },

  // Joy-Con (R)
  'Joy-Con (R)': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'rightshoulder': GameAction.r1,
    'rightstick': GameAction.horizontalAxis,
    'button_plus': GameAction.start,
    'button_9': GameAction.start,
  },

  // DualSense (PS5) / DualSense Edge
  'DualSense': {
    'cross': GameAction.confirm,
    'circle': GameAction.back,
    'square': GameAction.detail,
    'triangle': GameAction.favorite,
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_options': GameAction.select,
    'button_touchpad': GameAction.start,
    'button_menu': GameAction.start,
    'button_8': GameAction.select,
    'button_9': GameAction.start,
  },

  // DualShock 4 (PS4) - still very widely used
  'DualShock 4': {
    'cross': GameAction.confirm,
    'circle': GameAction.back,
    'square': GameAction.detail,
    'triangle': GameAction.favorite,
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_options': GameAction.select,
    'button_touchpad': GameAction.start,
  },

  // PlayStation controllers via USB on Windows (DirectInput/SDL2 name)
  'PS4 Controller': {
    'cross': GameAction.confirm,
    'circle': GameAction.back,
    'square': GameAction.detail,
    'triangle': GameAction.favorite,
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_options': GameAction.select,
    'button_touchpad': GameAction.start,
    'button_8': GameAction.select,
    'button_9': GameAction.start,
  },

  // PS5 controller via USB on Windows
  'PS5 Controller': {
    'cross': GameAction.confirm,
    'circle': GameAction.back,
    'square': GameAction.detail,
    'triangle': GameAction.favorite,
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_options': GameAction.select,
    'button_touchpad': GameAction.start,
    'button_8': GameAction.select,
    'button_9': GameAction.start,
  },

  // PS5 Access Controller
  'PS5 Access Controller': {
    'cross': GameAction.confirm,
    'circle': GameAction.back,
    'square': GameAction.detail,
    'triangle': GameAction.favorite,
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_options': GameAction.select,
    'button_touchpad': GameAction.start,
  },

  // PlayStation controllers on macOS/Linux (IOKit/evdev names)
  'Sony Interactive Entertainment Wireless Controller': {
    'cross': GameAction.confirm,
    'circle': GameAction.back,
    'square': GameAction.detail,
    'triangle': GameAction.favorite,
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_options': GameAction.select,
    'button_touchpad': GameAction.start,
  },

  // Logitech F310 (wired, D-Input / X-Input)
  'Logitech F310': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_6': GameAction.select,
    'button_7': GameAction.start,
    'button_8': GameAction.select,
    'button_9': GameAction.start,
  },

  // Logitech F710 (wireless)
  'Logitech F710': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_6': GameAction.select,
    'button_7': GameAction.start,
  },

  // Google Stadia Controller (Bluetooth mode)
  'Stadia': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // 8BitDo Pro 2 (D-Input and X-Input modes)
  '8BitDo Pro 2': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // 8BitDo Ultimate (2.4G and Bluetooth modes)
  '8BitDo Ultimate': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // PowerA Controllers (generic entry)
  'PowerA': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // Steam Controller (Valve)
  'Steam Controller': {
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // Pro Controller / Switch-style (macOS IOKit + Windows Bluetooth)
  'Pro Controller': {
    // macOS IOKit keys
    'a.circle': GameAction.confirm,
    'b.circle': GameAction.back,
    'x.circle': GameAction.detail,
    'y.circle': GameAction.favorite,
    'l.joystick - xAxis': GameAction.horizontalAxis,
    'l.joystick - yAxis': GameAction.verticalAxis,
    'dpad - xAxis': GameAction.horizontalAxis,
    'dpad - yAxis': GameAction.verticalAxis,
    'buttonMenu': GameAction.start,
    'buttonOptions': GameAction.select,
    'l.rectangle.roundedbottom': GameAction.l1,
    'r.rectangle.roundedbottom': GameAction.r1,
    // Windows Bluetooth / SDL2 keys
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_8': GameAction.select,
    'button_9': GameAction.start,
    'plus': GameAction.start,
    'minus': GameAction.select,
  },

  // Steam Deck
  'Steam Deck': {
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // GPD Win 4 (built-in handheld controller)
  'GPD Win 4': {
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
    'button_6': GameAction.start,
    'button_7': GameAction.select,
  },

  // Generic Controller
  'Generic Controller': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
  },

  // DualShock 3 (PS3) — still widely used on PC via USB/BT
  'DualShock 3': {
    'cross': GameAction.confirm,
    'circle': GameAction.back,
    'square': GameAction.detail,
    'triangle': GameAction.favorite,
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_8': GameAction.select,
    'button_9': GameAction.start,
    'button_select': GameAction.select,
    'button_start': GameAction.start,
  },

  // 8BitDo SN30 Pro / SN30 Pro+ (D-Input and X-Input)
  '8BitDo SN30 Pro': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
    'button_8': GameAction.select,
    'button_9': GameAction.start,
  },

  // 8BitDo Lite (Switch mode)
  '8BitDo Lite': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // 8BitDo Zero 2 (tiny portable controller)
  '8BitDo Zero 2': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // Razer Kishi (USB-C mobile controller)
  'Razer Kishi': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // Razer Wolverine (Xbox-style)
  'Razer Wolverine': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'start': GameAction.start,
    'back': GameAction.select,
    'button_6': GameAction.select,
    'button_7': GameAction.start,
  },

  // SteelSeries Nimbus (macOS / iOS — reports as "SteelSeries Nimbus")
  'SteelSeries Nimbus': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'button_menu': GameAction.start,
  },

  // SteelSeries Stratus (macOS / Windows Bluetooth)
  'SteelSeries Stratus': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // Backbone One (USB-C mobile controller, PlayStation edition)
  'Backbone One': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'cross': GameAction.confirm,
    'circle': GameAction.back,
    'square': GameAction.detail,
    'triangle': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // GameSir G7 (Xbox-licensed wired controller)
  'GameSir G7': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'start': GameAction.start,
    'back': GameAction.select,
    'button_6': GameAction.select,
    'button_7': GameAction.start,
  },

  // GameSir T4 (Bluetooth / 2.4G)
  'GameSir T4': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // Hori Fighting Commander (wired)
  'Hori Fighting Commander': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'button_6': GameAction.select,
    'button_7': GameAction.start,
  },

  // Hori Split Pad Pro (Switch handheld mode)
  'Hori Split Pad': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_plus': GameAction.start,
    'button_minus': GameAction.select,
  },

  // Nacon Revolution Pro (PS4/PS5 wired)
  'Nacon Revolution': {
    'cross': GameAction.confirm,
    'circle': GameAction.back,
    'square': GameAction.detail,
    'triangle': GameAction.favorite,
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_options': GameAction.select,
    'button_touchpad': GameAction.start,
    'button_8': GameAction.select,
    'button_9': GameAction.start,
  },

  // PDP Afterglow / Rock Candy (Xbox-style wired)
  'PDP Controller': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'start': GameAction.start,
    'back': GameAction.select,
    'button_6': GameAction.select,
    'button_7': GameAction.start,
  },

  // Scuf controllers (Xbox-style)
  'Scuf': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'start': GameAction.start,
    'back': GameAction.select,
    'button_6': GameAction.select,
    'button_7': GameAction.start,
  },

  // ASUS ROG Raikiri (Xbox-licensed)
  'ROG Raikiri': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'start': GameAction.start,
    'back': GameAction.select,
    'button_6': GameAction.select,
    'button_7': GameAction.start,
  },

  // Flydigi Vader / Apex (Chinese brand, popular in Asia)
  'Flydigi': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // Tencent GameSir / GuliKit (Hall effect sticks)
  'GuliKit': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // 8BitDo Ultimate C (budget wired/wireless)
  '8BitDo Ultimate C': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // Amazon Luna Controller (Bluetooth mode)
  'Luna Controller': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },

  // MSI Force GC30 (X-Input / D-Input)
  'MSI Force GC': {
    'button_0': GameAction.confirm,
    'button_1': GameAction.back,
    'button_2': GameAction.detail,
    'button_3': GameAction.favorite,
    'a': GameAction.confirm,
    'b': GameAction.back,
    'x': GameAction.detail,
    'y': GameAction.favorite,
    'dpad_up': GameAction.up,
    'dpad_down': GameAction.down,
    'dpad_left': GameAction.left,
    'dpad_right': GameAction.right,
    'leftshoulder': GameAction.l1,
    'rightshoulder': GameAction.r1,
    'leftstick': GameAction.horizontalAxis,
    'rightstick': GameAction.verticalAxis,
    'button_menu': GameAction.start,
    'button_options': GameAction.select,
  },
};

/// Fallback for unknown controllers - covers most XInput-style layouts
const Map<String, GameAction> kDefaultMapping = {
  'button_0': GameAction.confirm,
  'button_1': GameAction.back,
  'button_2': GameAction.detail,
  'button_3': GameAction.favorite,
  'a': GameAction.confirm,
  'b': GameAction.back,
  'x': GameAction.detail,
  'y': GameAction.favorite,

  // Mac/Switch Fallbacks
  'a.circle': GameAction.confirm,
  'b.circle': GameAction.back,
  'x.circle': GameAction.detail,
  'y.circle': GameAction.favorite,
  'cross': GameAction.confirm,
  'circle': GameAction.back,
  'square': GameAction.detail,
  'triangle': GameAction.favorite,
  'l.joystick - xAxis': GameAction.horizontalAxis,
  'l.joystick - yAxis': GameAction.verticalAxis,
  'dpad - xAxis': GameAction.horizontalAxis,
  'dpad - yAxis': GameAction.verticalAxis,
  'buttonMenu': GameAction.start,
  'buttonOptions': GameAction.select,
  'l.rectangle.roundedbottom': GameAction.l1,
  'r.rectangle.roundedbottom': GameAction.r1,

  // D-Pad
  'dpad_up': GameAction.up,
  'dpad_down': GameAction.down,
  'dpad_left': GameAction.left,
  'dpad_right': GameAction.right,
  'button_11': GameAction.up,
  'button_12': GameAction.down,
  'button_13': GameAction.left,
  'button_14': GameAction.right,

  // Shoulders / Triggers
  'leftshoulder': GameAction.l1,
  'rightshoulder': GameAction.r1,
  'button_4': GameAction.l1,
  'button_5': GameAction.r1,

  // Start / Select
  'button_menu': GameAction.start,
  'button_options': GameAction.select,
  'button_8': GameAction.select,
  'button_9': GameAction.start,
  'start': GameAction.start,
  'select': GameAction.select,
  'back': GameAction.select,
  'guide': GameAction.start,

  // Analog Sticks (axis)
  'leftstick': GameAction.horizontalAxis,
  'rightstick': GameAction.verticalAxis,
  'l.joystick': GameAction.horizontalAxis,
  'r.joystick': GameAction.verticalAxis,
};
